update_health_status:
  description: "Request the car to send latest sensor data."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
lock_vehicle:
  description: "Request the car to lock."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
unlock_vehicle:
  description: "Request the car to unlock."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
reset_alarm:
  description: "Reset the vehicle alarm."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
honk_blink:
  description: "Sound the horn and flash the lights."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
start_vehicle:
  description: "Start the vehicle engine and set climate temp."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
    target_value:
      name: Targert Temperature
      description: "The temperature to set (15.5 - 28.5C or 58 - 84F based on local HA units)."
      example: "21.0"
      default: 21
      required: true
      selector:
        number:
          min: 15.5
          max: 28.5
          step: 0.5
          unit_of_measurement: °C
stop_vehicle:
  description: "Stop the vehicle engine."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
start_charging:
  description: "Start vehicle charging."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
stop_charging:
  description: "Stop vehicle charging."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
set_departure_timer:
  description: "Set a departure timer."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    departure_datetime:
      name: "Departure time"
      description: "Date and time of departure."
      example: "2023-05-10 18:45:00"
      required: true
      selector:
        datetime:
delete_departure_timer:
  description: "Delete the departure timer."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
start_preconditioning:
  description: "Start vehicle preconditioning and set temp."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    target_temperature:
      name: Target Temperature
      description: "The temperature to set (15.5 - 28.5C)."
      example: 21
      default: 21
      required: true
      selector:
        number:
          min: 15.5
          max: 28.5
          step: 0.5
          unit_of_measurement: °C
stop_preconditioning:
  description: "Stop vehicle preconditioning."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
set_max_charge_level:
  description: "Set vehicle maximum charge level."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    max_charge_level:
      name: "Max Charge Level"
      description: "The percentage to charge to."
      example: 85
      default: 85
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
set_one_off_max_charge_level:
  description: "Set vehicle maximum charge level (one off)."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    max_charge_level:
      name: "Max Charge Level"
      description: "The percentage to charge to."
      example: 85
      default: 85
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
disable_privacy_mode:
  description: "Enable journey recording"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
enable_privacy_mode:
  description: "Disable journey recording"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
enable_guardian_mode:
  description: "Enable guardian moode"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    expiration_time:
      name: "Expiration Time"
      description: "Turn on guardian mode until"
      example: "2023-05-10 18:45:00"
      required: true
      selector:
        datetime:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
disable_guardian_mode:
  description: "Disable guardian moode"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
enable_service_mode:
  description: "Enable service moode"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    expiration_time:
      name: "Expiration Time"
      description: "Turn on service mode until"
      example: "2023-05-10 18:45:00"
      required: true
      selector:
        datetime:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
disable_service_mode:
  description: "Disable service moode"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
enable_transport_mode:
  description: "Enable transport moode"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    expiration_time:
      name: "Expiration Time"
      description: "Turn on transport mode until"
      example: "2023-05-10 18:45:00"
      required: true
      selector:
        datetime:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
disable_transport_mode:
  description: "Disable transport moode"
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      required: false
      selector:
        text:
