update_health_status:
  description: "Request the car to send latest sensor data."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
lock_vehicle:
  description: "Request the car to lock."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      default: "0000"
      required: true
      selector:
        text:
unlock_vehicle:
  description: "Request the car to unlock."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      default: "0000"
      required: true
      selector:
        text:
reset_alarm:
  description: "Reset the vehicle alarm."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      default: "0000"
      required: true
      selector:
        text:
honk_blink:
  description: "Sound the horn and flash the lights."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
start_vehicle:
  description: "Start the vehicle engine and set climate temp."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      default: "0000"
      required: true
      selector:
        text:
    target_value:
      name: Targert Temperature
      description: "The temperature to set (15.5 - 28.5C or 58 - 84F based on local HA units)."
      example: "21.0"
      default: 21
      required: true
      selector:
        number:
          min: 15.5
          max: 28.5
          step: 0.5
          unit_of_measurement: °C
stop_vehicle:
  description: "Stop the vehicle engine."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    pin:
      name: Pin
      description: "The pin set for your vehicle."
      example: "1234"
      default: "0000"
      required: true
      selector:
        text:
start_charging:
  description: "Start vehicle charging."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
stop_charging:
  description: "Stop vehicle charging."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
start_preconditioning:
  description: "Start vehicle preconditioning and set temp."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    target_temperature:
      name: Target Temperature
      description: "The temperature to set (15.5 - 28.5C)."
      example: 21
      default: 21
      required: true
      selector:
        number:
          min: 15.5
          max: 28.5
          step: 0.5
          unit_of_measurement: °C
stop_preconditioning:
  description: "Stop vehicle preconditioning."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
set_max_charge_level:
  description: "Set vehicle maximum charge level."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    max_charge_level:
      name: "Max Charge Level"
      description: "The percentage to charge to."
      example: 85
      default: 85
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
set_one_off_max_charge_level:
  description: "Set vehicle maximum charge level (one off)."
  target:
    entity:
      integration: jlrincontrol
      domain: sensor
  fields:
    max_charge_level:
      name: "Max Charge Level"
      description: "The percentage to charge to."
      example: 85
      default: 85
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
